name: Mi primer workflow             
on:                        
  push:                    
    branches:
      - main               
  workflow_dispatch:   
  
jobs:                      
  saludar:                  
    runs-on: ubuntu-latest 

    steps:                 
      - name: hola
        run: echo "Hola, soy Ruben"    

      - name: fecha
        run: echo $(date +"Hora:Minutos:Segundos Dia/Mes/Año") 
        
      - name: cont
        run:  ls 
